analyzer:
  strong-mode: true
  exclude:
    - 'lib/generators/**'
    - 'lib/src/old/**'
    - 'lib/templates/rdf-minimal/**'
    - 'lib/templates/rdf-project/**'
    - 'lib/templates/rdf-server/**'
    - 'lib/templates/rdf-skeletons/**'
    - 'lib/templates/web-stagexl/**'

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
  errors:
    unused_import: error
    unused_element: info
    unused_local_variable: info
    dead_code: info
linter:
  rules:
    # Errors
    - avoid_empty_else
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

    # Style
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - only_throw_errors
    - prefer_final_fields
    - prefer_is_not_empty
    - prefer_single_quotes
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_brace_in_string_interps
