analyzer:
  exclude:
    - lib/generators/**
    - lib/src/old/**
    - lib/templates/rdf-minimal/**
    - lib/templates/rdf-project/**
    - lib/templates/rdf-server/**
    - lib/templates/rdf-skeletons/**
    - lib/templates/web-stagexl/**
  errors:
    unused_import: error
    unused_element: info
    unused_local_variable: info
    dead_code: info

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    # Errors
    - avoid_empty_else
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

