name: acanvas_generator
version: 0.11.0
authors:
  - Nils Döhring <nilsdoehring@gmail.com>
description: |
  A CLI to generate skeletons of Canvas/WebGL projects based on StageXL and Acanvas. Includes generators for in-project asset-collection, creation of commands, views, plugins.
homepage: https://github.com/acanvas/acanvas-generator
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: '>=1.5.0 <2.0.0'
  archive: any
  crypto: '>=2.0.0 <3.0.0'
  http: '>=0.11.0 <0.12.0'
  path: '>=1.3.0 <2.0.0'
  usage: '>=3.0.0 <4.0.0'
  resource: any
dependency_overrides:
  convert: '>=2.0.1'

dev_dependencies:
  #browser: any
  #ghpages_generator: any
  grinder: any
  test: any
executables:
  acgen: acanvas_generator
