name: acanvas_generator
version: 0.10.0-dev
authors:
- Nils Döhring <nilsdoehring@gmail.com>
description: |
  A CLI to generate skeletons of Canvas/WebGL projects based on StageXL and Acanvas. Supports in-project asset-collection, and generation of commands, views, plugins.
homepage: https://github.com/block-forest/acanvas-generator
environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'
dependencies:
  args: '>=0.12.0+1 <0.13.0'
  archive: any
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.11.0 <0.12.0'
  path: '>=1.3.0 <2.0.0'
  usage: '>=1.0.0 <2.0.0'
  resource: any
dependency_overrides:
  convert: '>=2.0.1'

dev_dependencies:
  browser: any
  ghpages_generator: any
  grinder: '>=0.7.0 <0.7.1'
  unittest: any
executables:
  acgen: acanvas_generator
