part of acanvas_template;

///  The AcBootstrap class manages instantiation of and programmatic additions to our [ApplicationContext].
///  Most often, you will instantiate and load this class in [Entrypoint]

class Plugins {
  int _exampleOrder;
  List<IObjectFactoryPostProcessor> plugins;

  Plugins() {
    //----------------------------
    //Index for order of Examples. Starts with 1 because 0 is reserved for Home Page.
    _exampleOrder = 1;

    // The Plugins we want to use

    plugins = <IObjectFactoryPostProcessor>[
      //----------------------------

      // Mandatory Plugins

      new StatePlugin(),
      new ScreenDisplaylistPlugin(),

      //----------------------------

      //Optional Plugins

      new IOPlugin(),

      //google
      //new GooglePlugin(),

      //facebook
     // new FacebookPlugin(),

      //ugc
      new UGCPlugin(),

      //babylon
      new BabylonPlugin(autoInit: true),

      //----------------------------

      // Autogenerated Plugins

      // ## PLUGIN INSERTION PLACEHOLDER - DO NOT REMOVE ## //

      //----------------------------

      // Examples

      //bitmapfont-example
      new BitmapFontExamplePlugin(_exampleOrder++),

      //stagexl-example
      new StagexlExamplePlugin(_exampleOrder++),

      //material-example
      new MaterialExamplePlugin(_exampleOrder++),

      //dragonbones-example
      new DragonBonesExamplePlugin(_exampleOrder++),

      //gaf-example
      new GAFExamplePlugin(_exampleOrder++),

      //spine-example
      new SpineExamplePlugin(_exampleOrder++),

      //flump-example
      new FlumpExamplePlugin(_exampleOrder++),

      //isometric-example
      new IsometricExamplePlugin(_exampleOrder++),

      //particle-example
      new ParticleExamplePlugin(_exampleOrder++),

      //facebook-example
     // new FacebookExamplePlugin(_exampleOrder++),

      //google-example
      //new GoogleExamplePlugin(_exampleOrder++),

      //physics-example
      new PhysicsExamplePlugin(_exampleOrder++),

      //babylon-example
      new BabylonExamplePlugin(_exampleOrder++),

      //moppiflower-example
      new MoppiFlowerExamplePlugin(_exampleOrder++),

      //ugc-example
      new UGCExamplePlugin(_exampleOrder++),

      // Our project. Contains the Home Page. It's a plugin, too!
      new Project()
    ];
  }
}
