# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:

  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
          - web/project.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
           # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
           # - --dump-info
           # - --fast-startup
            - --minify
            - --no-frequency-based-minification
            - --no-source-maps
            - --show-package-warnings
            - --trust-primitives
            - --trust-type-annotations

#builders:
##TODO: create a separate repo containing just examples, have builder pull them from there
##TODO: make builder configurable so that you only have to add plugins here, with the rest working automagically
#  templateBuilder:
#    import: "package:rockdot_template/rockdot_template_builder.dart"
#    builder_factories: ["templateBuilder"]
#    build_extensions: {".template.html": [".html"],
#                      ".template.php": [".php"],
#                      ".template.js": [".js"],
#                      ".template.dart": [".dart"],
#                      ".template.properties": [".css"],
#                      ".template.css": [".properties"]}
#    build_to: source
#    auto_apply: root_package
#    defaults:
#      dev_options: {"mode" : "debug"}
#      release_options: {"mode" : "release"}
#      generate_for:
#        # Only apply to .template.* files in the web directory
#        include:
#        - web/**.template.*
