part of dragonbones_example;

///This class is autogenerated by executing 'pub run collect_assets' in your project's root.
///It collects all images from web/assets
class DragonBonesAssets {
  static BitmapData get ani1 {
    return _singleton.mgr.getBitmapData("ani1");
  }

  static BitmapData get ani2 {
    return _singleton.mgr.getBitmapData("ani2");
  }

  static BitmapData get banner {
    return _singleton.mgr.getBitmapData("banner");
  }

  static BitmapData get feature {
    return _singleton.mgr.getBitmapData("feature");
  }

  static BitmapData get more1 {
    return _singleton.mgr.getBitmapData("more1");
  }

  static BitmapData get more10 {
    return _singleton.mgr.getBitmapData("more10");
  }

  static BitmapData get more11 {
    return _singleton.mgr.getBitmapData("more11");
  }

  static BitmapData get more12 {
    return _singleton.mgr.getBitmapData("more12");
  }

  static BitmapData get more2 {
    return _singleton.mgr.getBitmapData("more2");
  }

  static BitmapData get more3 {
    return _singleton.mgr.getBitmapData("more3");
  }

  static BitmapData get more4 {
    return _singleton.mgr.getBitmapData("more4");
  }

  static BitmapData get more5 {
    return _singleton.mgr.getBitmapData("more5");
  }

  static BitmapData get more6 {
    return _singleton.mgr.getBitmapData("more6");
  }

  static BitmapData get more7 {
    return _singleton.mgr.getBitmapData("more7");
  }

  static BitmapData get more8 {
    return _singleton.mgr.getBitmapData("more8");
  }

  static BitmapData get more9 {
    return _singleton.mgr.getBitmapData("more9");
  }

  static BitmapData getBitmapData(String id) {
    return _singleton.mgr.getBitmapData(id);
  }

  ResourceManager mgr;
  static final DragonBonesAssets _singleton = new DragonBonesAssets._internal();
  DragonBonesAssets._internal() {
    mgr = new ResourceManager();
  }

  factory DragonBonesAssets() {
    return _singleton;
  }

  static Future load() async {
    _singleton.mgr.addBitmapData("ani1", "assets/dragonbones/home/ani1.png");
    _singleton.mgr.addBitmapData("ani2", "assets/dragonbones/home/ani2.png");
    _singleton.mgr.addBitmapData("banner", "assets/dragonbones/home/banner.png");
    _singleton.mgr.addBitmapData("feature", "assets/dragonbones/home/feature.png");
    _singleton.mgr.addBitmapData("more1", "assets/dragonbones/home/more1.png");
    _singleton.mgr.addBitmapData("more10", "assets/dragonbones/home/more10.png");
    _singleton.mgr.addBitmapData("more11", "assets/dragonbones/home/more11.png");
    _singleton.mgr.addBitmapData("more12", "assets/dragonbones/home/more12.png");
    _singleton.mgr.addBitmapData("more2", "assets/dragonbones/home/more2.png");
    _singleton.mgr.addBitmapData("more3", "assets/dragonbones/home/more3.png");
    _singleton.mgr.addBitmapData("more4", "assets/dragonbones/home/more4.png");
    _singleton.mgr.addBitmapData("more5", "assets/dragonbones/home/more5.png");
    _singleton.mgr.addBitmapData("more6", "assets/dragonbones/home/more6.png");
    _singleton.mgr.addBitmapData("more7", "assets/dragonbones/home/more7.png");
    _singleton.mgr.addBitmapData("more8", "assets/dragonbones/home/more8.png");
    _singleton.mgr.addBitmapData("more9", "assets/dragonbones/home/more9.png");

    await _singleton.mgr.load();
  }
}
