part of acanvas_template;

///This class is autogenerated by executing 'pub run collect_assets' in your project's root.
///It collects all images from web/assets
class Assets {
  static BitmapData get acanvas {
    return _singleton.mgr.getBitmapData("acanvas");
  }

  static BitmapData get logo_acanvas_small {
    return _singleton.mgr.getBitmapData("logo_acanvas_small");
  }

  static BitmapData get dog {
    return _singleton.mgr.getBitmapData("dog");
  }

  ResourceManager mgr = new ResourceManager();
  static BitmapData getBitmapData(String id) {
    return _singleton.mgr.getBitmapData(id);
  }

  static final Assets _singleton = new Assets._internal();

  factory Assets() {
    return _singleton;
  }

  Assets._internal() {}

  static Future load() async {
    _singleton.mgr.addBitmapData("dog", "assets/autoload/dog.jpg");
    _singleton.mgr.addBitmapData("acanvas", "assets/autoload/acanvas@1x.png");
    _singleton.mgr.addBitmapData(
        "logo_acanvas_small", "assets/autoload/logo_acanvas_small@1x.png");

    await _singleton.mgr.load();
  }
}
